#!/usr/bin/env python3
''' -*- coding: utf-8 -*-
 File: triage_tool/triage_tool.py
 Author: Elijah Anakalea-Buckley
 Purpose: Triage aspects of any observatory system or instrument to provide
          a quick overview of the system health and status at any point.
          Specifically designed for execution at a crash or issue during
          observation and potencially adapts to monitoring of system health
          over time.

NOTE:: pip install the items below;not included in python standard packages
       pip install pyscreenshot
       pip install psutil
       pip install vncdotool
       pip install pillow
                       -Elijah Anakalea-Buckley
'''
import argparse
from triage_package.triage_tool import Triagetools

#Fill out section then run like a CLI executable!###############
CONFIG_PATH = "triage_package/triage.ini"

################################################################

def run_triage():
    '''Executable file for use on the Command line'''
    parser = argparse.ArgumentParser(description="Gecko command-line tool")

    parser = argparse.ArgumentParser(
        description="""
            Gecko Triage Tool

            A command-line utility to collect system and application logs, take screenshots, 
            grab science images, and optionally send a compressed report via email.

            You can either:
            1) Initialize the application (--initialize) to configure settings.
            2) Run a triage report (--message "description") to gather logs and send a report.
                    """,
                    formatter_class=argparse.RawTextHelpFormatter
                )

    # Mutually exclusive: either initialize or provide a message
    group = parser.add_mutually_exclusive_group(required=True)

    group.add_argument(
        "-init","--initialize",
        action="store_true",
        help="Initialize the application"
    )

    group.add_argument(
        "-m", "--message",
        type=str,
        help="Run the triage workflow with a message describing the issue. "
             "Example: --message 'GPU overheating issue observed today'"
    )

    args = parser.parse_args()

    if args.initialize:
        gecko = Triagetools(config=CONFIG_PATH, init=True)
        print('\nInitialization complete!')
        print('You can now run the GUI or use:\n  gecko -m "your issue message" \n')

    elif args.message:
        gecko = Triagetools(config=CONFIG_PATH, message=args.message)
        print(f"Running triage workflow for message: {args.message}\n")
        gecko.gather_system_info()
        gecko.gather_logs()
        gecko.comb_logs()
        gecko.take_screenshots()
        gecko.grab_science_image()
        gecko.compress_report()

        if gecko.email_alerts:
            gecko.send_report()
        print("\nTriage workflow complete!")


if __name__ == "__main__":
    run_triage()
